- name: Build cEOS EVPN Symmetric IRB Fabric (eBGP Overlay and eBGP Underlay)
  hosts: DC1_FABRIC

  vars:
    eos_config_dir: '{{ output_dir }}/{{ eos_config_dir_name }}'

  tasks:
    - name: Replace configuration with intended configuration
      eos_config:
        src: "{{ eos_config_dir }}/{{ inventory_hostname }}.cfg"
        replace: config
        save_when: modified
      tags: [provision]
